name: Lancelot
description: Hello
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  firebase_core: any
  firebase_messaging: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  http: any
  syncfusion_flutter_sliders: any
  flutter_datetime_picker: any
  multi_select_flutter: any
  flutter_tindercard: any
  staggered_grid_view_flutter: any
  flutter_staggered_animations: any
  flutter_carousel_slider: any
  cached_network_image: any
  loading_animation_widget: any
  image_picker: any
  google_fonts: any
  bottom_sheet: any
  avatar_glow: any
  flutter_staggered_grid_view: any
  like_button: any
  shared_preferences: any
  ndialog: any
  lottie: any
  image_cropper: any
  url_launcher: any
  flutter_launcher_icons: any
  zoom_tap_animation: any
  flutter_colors_border: any
  animator: any
  animate_gradient: any
  delayed_display: any
  bubble: any
  drop_shadow: any
  shimmer_animation: any
  get: any
  get_it: any
  rive:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter_icons:
  image_path: "images/icons/logo_icon_app.jpg"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/logo_icon_app.jpg
    - images/rive/animation_rive_icons