name: Lancelot
description: Hello
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  http: ^0.13.5
  syncfusion_flutter_sliders: ^20.4.52
  flutter_datetime_picker: ^1.5.1
  multi_select_flutter: ^4.1.3
  flutter_tindercard: ^0.2.0
  staggered_grid_view_flutter: ^0.0.4
  flutter_staggered_animations: ^1.1.1
  flutter_carousel_slider: ^1.1.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^3.0.1
  bottom_sheet: ^3.1.2
  avatar_glow: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  image_picker: ^0.8.6+1
  like_button: ^2.0.5
  firebase_storage: ^11.0.10
  shared_preferences: ^2.0.17
  ndialog: ^4.2.3
  lottie: ^2.2.0
  image_cropper: ^3.0.1
  url_launcher: ^6.1.8
  flutter_launcher_icons: ^0.11.0
  glowstone: ^0.0.2
  zoom_tap_animation: ^1.1.0
  flutter_colors_border: ^0.0.3+2
  animator: ^3.2.0
  animate_gradient: ^0.0.2
  delayed_display: ^2.0.0
  bubble: 1.2.1
  drop_shadow: ^0.0.2+1
  shimmer_animation: ^2.1.0+1
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter_icons:
  image_path: "images/icons/logo_icon_app.jpg"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/logo_icon_app.jpg