name: Lancelot
description: Hello
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  http: ^0.13.5
  syncfusion_flutter_sliders: ^21.1.37
  flutter_datetime_picker: ^1.5.1
  multi_select_flutter: ^4.1.3
  flutter_tindercard: ^0.2.0
  staggered_grid_view_flutter: ^0.0.4
  flutter_staggered_animations: ^1.1.1
  flutter_carousel_slider: ^1.1.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  image_picker: ^0.8.7+1
  google_fonts: ^4.0.3
  bottom_sheet: ^3.1.2
  avatar_glow: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  like_button: ^2.0.5
  shared_preferences: ^2.0.20
  ndialog: ^4.3.0
  lottie: ^2.3.1
  image_cropper: ^3.0.2
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.12.0
  zoom_tap_animation: ^1.1.0
  flutter_colors_border: ^0.0.3+2
  animator: ^3.2.0
  animate_gradient: ^0.0.2
  delayed_display: ^2.0.0
  bubble: 1.2.1
  drop_shadow: ^0.1.0
  shimmer_animation: ^2.1.0+1
  get: ^4.6.5
  get_it: ^7.2.0
  rive: ^0.10.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter_icons:
  image_path: "images/icons/logo_icon_app.jpg"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/logo_icon_app.jpg
    - images/rive/animation_rive_icons