// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsasRpgdcsqdnM5PjnwBIyUaUBq79OK0M',
    appId: '1:184301190803:android:8501e05d30d43946201766',
    messagingSenderId: '184301190803',
    projectId: 'karakol-tinder',
    storageBucket: 'karakol-tinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdKY6TFlO5Z0C9HxP975FNj7HfrbbF2o',
    appId: '1:184301190803:ios:cc0c528fa2d9c62d201766',
    messagingSenderId: '184301190803',
    projectId: 'karakol-tinder',
    storageBucket: 'karakol-tinder.appspot.com',
    androidClientId: '184301190803-qhehhs04fuikrqodou7mveuhl6foicuv.apps.googleusercontent.com',
    iosClientId: '184301190803-pemf02lsrbsud6gua7idm96fvnph6dhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lancelot',
  );
}
